# Generated by Django 5.1.1 on 2024-11-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_financ', '0002_noticia_publicacao_delete_taxamercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
